# .github/workflows/main.yml

on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: rich.castro@achesongroup.com
        ORIGIN_TIMESTAMP: 2020/05/01
        MAX_DAYS: 90
        MIN_COMMITS_PER_DAY: 0
        MAX_COMMITS_PER_DAY: 2
        INCLUDE_WEEKENDS: false
        
